USE [master]
GO
/****** Object:  Database [CloudUtil]    Script Date: 3/26/2021 3:53:08 PM ******/
CREATE DATABASE [CloudUtil]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CloudUtil', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\CloudUtil.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CloudUtil_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\CloudUtil_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [CloudUtil] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CloudUtil].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CloudUtil] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CloudUtil] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CloudUtil] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CloudUtil] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CloudUtil] SET ARITHABORT OFF 
GO
ALTER DATABASE [CloudUtil] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CloudUtil] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CloudUtil] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CloudUtil] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CloudUtil] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CloudUtil] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CloudUtil] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CloudUtil] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CloudUtil] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CloudUtil] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CloudUtil] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CloudUtil] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CloudUtil] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CloudUtil] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CloudUtil] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CloudUtil] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CloudUtil] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CloudUtil] SET RECOVERY FULL 
GO
ALTER DATABASE [CloudUtil] SET  MULTI_USER 
GO
ALTER DATABASE [CloudUtil] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CloudUtil] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CloudUtil] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CloudUtil] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CloudUtil] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CloudUtil] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'CloudUtil', N'ON'
GO
ALTER DATABASE [CloudUtil] SET QUERY_STORE = OFF
GO
USE [CloudUtil]
GO
/****** Object:  Table [dbo].[tbleUsers]    Script Date: 3/26/2021 3:53:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbleUsers](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[UserName] [varchar](100) NULL,
	[EmailId] [varchar](100) NULL,
	[CreatedDate] [datetime] NULL,
	[UpdatedDate] [datetime] NULL,
	[DeletedDate] [datetime] NULL,
	[CreatedBy] [bigint] NULL,
	[UpdatedBy] [bigint] NULL,
	[DeletedBy] [bigint] NULL,
	[IsActive] [bit] NULL,
	[IsDelete] [bit] NULL,
 CONSTRAINT [PK_tbleUsers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[tbleUsers] ON 
GO
INSERT [dbo].[tbleUsers] ([Id], [UserName], [EmailId], [CreatedDate], [UpdatedDate], [DeletedDate], [CreatedBy], [UpdatedBy], [DeletedBy], [IsActive], [IsDelete]) VALUES (1, N'VIjay', N'vijayasankar.vikraman@hrblock.com', CAST(N'2021-03-25T13:57:20.987' AS DateTime), NULL, NULL, NULL, NULL, NULL, 1, 0)
GO
SET IDENTITY_INSERT [dbo].[tbleUsers] OFF
GO
ALTER TABLE [dbo].[tbleUsers] ADD  CONSTRAINT [DF_tbleUsers_CreatedDate]  DEFAULT (getdate()) FOR [CreatedDate]
GO
USE [master]
GO
ALTER DATABASE [CloudUtil] SET  READ_WRITE 
GO
